from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
# Replace an existing bottom nav, or create one if a previous compact build removed it.
nav=re.compile(r'<div\s+class=["\']nav["\'][^>]*>.*?</div>',re.S|re.I)
new_nav='''<div class="nav" id="sniperNav"><button type="button" data-nav="dashboard"><b>🏠</b><span>Dashboard</span></button><button type="button" data-nav="scanner"><b>🎯</b><span>Scanner</span></button><button type="button" data-nav="watchlist"><b>👁️</b><span>Watchlist</span></button><button type="button" data-nav="news"><b>📰</b><span>News</span></button><button type="button" data-nav="settings"><b>⚙️</b><span>Settings</span></button></div>'''
if nav.search(s):
    s=nav.sub(new_nav,s,count=1)
elif 'id="sniperNav"' not in s:
    s=s.replace('</body>',new_nav+'</body>',1)
css='''<style id="functional-nav-css">#sniperNav button{border:0;background:transparent;padding:5px 10px;color:#6e7f94;cursor:pointer;touch-action:manipulation}#sniperNav button b{display:block;font-size:17px;color:#0b2a52;margin-bottom:1px}#sniperNav button.active span,#sniperNav button.active b{color:#087dca}.nav-modal{position:fixed;inset:0;background:#071b3a55;z-index:30;display:none;align-items:flex-end;justify-content:center}.nav-modal.open{display:flex}.nav-sheet{width:min(540px,100%);background:#fff;border-radius:20px 20px 0 0;padding:16px;box-shadow:0 -10px 30px #10213b25}.nav-sheet h3{margin:0 0 8px}.nav-sheet p{font-size:12px;color:#66778d;line-height:1.5}.nav-close{width:100%;padding:11px;border:1px solid #dce5ef;border-radius:12px;background:#f3f7fb;font-weight:800}#swingV2.nav-focus{outline:2px solid #087dca}</style>'''
if 'id="functional-nav-css"' not in s:s=s.replace('</head>',css+'</head>',1)
modal='''<div class="nav-modal" id="navModal"><div class="nav-sheet"><h3 id="navModalTitle">Settings</h3><div id="navModalBody"></div><button class="nav-close" id="navClose">Close</button></div></div>'''
if 'id="navModal"' not in s:s=s.replace('</body>',modal+'</body>',1)
js='''<script id="functional-nav-js">(function(){const nav=document.getElementById('sniperNav'),modal=document.getElementById('navModal'),title=document.getElementById('navModalTitle'),body=document.getElementById('navModalBody');if(!nav)return;function active(k){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.nav===k))}function getSaved(){try{return JSON.parse(localStorage.getItem('sniperWatchlist')||'[]')}catch(e){return[]}}function show(k){active(k);if(k==='dashboard'){window.scrollTo({top:0,behavior:'smooth'});return}if(k==='scanner'){const el=document.getElementById('swingV2')||document.getElementById('swingScannerPanel');if(el){el.scrollIntoView({behavior:'smooth',block:'start'});el.classList.add('nav-focus');setTimeout(()=>el.classList.remove('nav-focus'),1200)}return}if(!modal)return;modal.classList.add('open');if(k==='watchlist'){title.textContent='👁️ Watchlist';const saved=getSaved();body.innerHTML=saved.length?'<p>'+saved.map(x=>{const o=typeof x==='string'?{symbol:x,lifecycle:'WATCH'}:x;return '• <b>'+String(o.symbol||'—')+'</b> — '+String(o.lifecycle||'WATCH')}).join('<br>')+'</p><p>Saved scanner candidates stay on this device.</p>':'<p>Your watchlist is empty. Tap Watchlist on a swing candidate to save it.</p>'}else if(k==='news'){title.textContent='📰 News Radar';body.innerHTML='<p>Use the News Radar and News Intelligence sections for current headlines, sentiment and risk context. News is context only, not a standalone CALL/PUT trigger.</p>'}else{title.textContent='⚙️ Settings';body.innerHTML='<p><b>Data:</b> Upstox market data.</p><p><b>Refresh:</b> Live cockpit and swing scanner refresh automatically.</p><p><b>Risk:</b> Capital and Risk % feed the position-size helper.</p><p><b>Safety:</b> Conflicting confirmation = NO TRADE. Setups are probabilistic/educational.</p>'}}nav.addEventListener('click',e=>{const b=e.target.closest('button[data-nav]');if(b)show(b.dataset.nav)});document.getElementById('navClose')?.addEventListener('click',()=>modal.classList.remove('open'));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});active('dashboard')})();</script>'''
if 'id="functional-nav-js"' not in s:s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
