from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
css='''<style id="intel-panels-css">.intel-panel{margin-top:6px;padding:8px;border:1px solid #dce5ef;border-radius:10px;background:#fff}.intel-title{font-size:10px;font-weight:900;color:#10213b}.intel-line{font-size:8px;color:#52657d;padding:5px 0;border-bottom:1px solid #edf1f5}.intel-line:last-child{border:0}.intel-badge{display:inline-block;padding:3px 5px;border-radius:6px;background:#eef4fa;font-weight:900;margin-right:4px}.intel-high{color:#d94058}.intel-med{color:#bd8610}.intel-low{color:#079b6a}.intel-muted{font-size:8px;color:#718198;margin-top:5px}</style>'''
if 'id="intel-panels-css"' not in s:s=s.replace('</head>',css+'</head>',1)
panel='''<div class="intel-panel" id="eventTrackerPanel"><div class="intel-title">📅 EVENT TRACKER</div><div id="eventTrackerList">Loading market events…</div></div>\n<div class="intel-panel" id="smartMoneyPanel"><div class="intel-title">🐋 SMART MONEY ACTIVITY</div><div id="smartMoneyList">Loading institutional-flow proxy…</div></div>'''
if 'id="eventTrackerPanel"' not in s:
    marker='<div class="one-screen-details"'
    if marker in s:s=s.replace(marker,panel+'\n'+marker,1)
    else:s=s.replace('</main>',panel+'\n</main>',1)
js='''<script id="intel-panels-js">(function(){function esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}async function loadEvents(){const b=document.getElementById('eventTrackerList');if(!b)return;try{const d=await (await fetch('/api/events?ts='+Date.now(),{cache:'no-store'})).json();b.innerHTML=d.ok&&d.events?.length?d.events.slice(0,5).map(x=>`<div class="intel-line"><span class="intel-badge ${x.risk==='HIGH'?'intel-high':x.risk==='MEDIUM'?'intel-med':'intel-low'}">${esc(x.category)} • ${esc(x.risk)}</span>${esc(x.title)}</div>`).join(''):'<div class="intel-muted">No fresh event context.</div>'}catch(e){b.innerHTML='<div class="intel-muted">Event tracker unavailable.</div>'}}async function loadSmart(){const b=document.getElementById('smartMoneyList');if(!b)return;try{const d=await (await fetch('/api/smart-money?ts='+Date.now(),{cache:'no-store'})).json(),a=d.activity||{};b.innerHTML=`<div class="intel-line"><span class="intel-badge">BIAS</span><b>${esc(a.bias)}</b> • PCR ${esc(a.pcr)} • Put OI ${esc(a.total_put_oi)} • Call OI ${esc(a.total_call_oi)}</div><div class="intel-line">${esc((d.signals||[]).join(' • '))}</div><div class="intel-muted">Proxy only — exact institutional intent cannot be inferred from public market data.</div>`}catch(e){b.innerHTML='<div class="intel-muted">Smart money tracker unavailable.</div>'}}loadEvents();loadSmart();setInterval(loadEvents,60000);setInterval(loadSmart,30000);})();</script>'''
if 'id="intel-panels-js"' not in s:s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
