from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
css='''<style id="risk-engine-css">.risk-box{margin-top:8px;padding:9px;border:1px solid #dce5ef;border-radius:10px;background:#f7f9fc}.risk-title{font-size:9px;font-weight:900;color:#10213b}.risk-controls{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px}.risk-controls label{font-size:8px;color:#718198}.risk-controls input{width:100%;margin-top:2px;padding:7px;border:1px solid #d6e1eb;border-radius:8px;font-size:10px;font-weight:800}.risk-result{margin-top:7px;display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.risk-k{background:#fff;border-radius:8px;padding:6px}.risk-k small{display:block;font-size:7px;color:#718198}.risk-k b{display:block;font-size:10px;margin-top:2px}.risk-note{font-size:8px;color:#718198;margin-top:6px;line-height:1.35}</style>'''
if 'id="risk-engine-css"' not in s:s=s.replace('</head>',css+'</head>',1)
box='''<div class="risk-box" id="riskEngine"><div class="risk-title">🛡️ RISK ENGINE • POSITION SIZE</div><div class="risk-controls"><label>Capital ₹<input id="riskCapital" type="number" inputmode="decimal" value="100000" min="0"></label><label>Risk %<input id="riskPct" type="number" inputmode="decimal" value="1" min="0" max="5" step="0.1"></label></div><div class="risk-result"><div class="risk-k"><small>Risk Amount</small><b id="riskAmount">₹1,000</b></div><div class="risk-k"><small>Qty</small><b id="riskQty">—</b></div><div class="risk-k"><small>Max Loss</small><b id="riskLoss">—</b></div></div><div class="risk-note" id="riskNote">Quantity = Risk Amount ÷ (Entry − SL). Only BUY setups with valid Entry/SL are sized.</div></div>'''
if 'id="riskEngine"' not in s:
    marker='</main>'
    s=s.replace(marker,box+'\n'+marker,1)
js='''<script id="risk-engine-js">(function(){function n(id){return document.getElementById(id)}function money(v){return Number.isFinite(v)?'₹'+Math.round(v).toLocaleString('en-IN'):'—'}function calc(){const cap=Math.max(0,Number(n('riskCapital')?.value)||0),pct=Math.min(5,Math.max(0,Number(n('riskPct')?.value)||0)),amt=cap*pct/100;const cards=document.querySelectorAll('.swing-card');let entry=null,sl=null,action='WAIT';cards.forEach(c=>{if(entry==null){const t=c.innerText||'';const m=t.match(/Entry\\s+₹?([0-9,.]+)/i),z=t.match(/SL\\s+₹?([0-9,.]+)/i),a=t.match(/\\b(BUY|WAIT|AVOID)\\b/i);if(m&&z){entry=Number(m[1].replace(/,/g,''));sl=Number(z[1].replace(/,/g,''));action=a?a[1]:'WAIT'}}});const riskPer=entry&&sl&&entry>sl?entry-sl:0,qty=riskPer?Math.floor(amt/riskPer):0;n('riskAmount').textContent=money(amt);n('riskQty').textContent=action==='BUY'&&qty>0?qty.toLocaleString('en-IN'):'—';n('riskLoss').textContent=action==='BUY'&&qty>0?money(qty*riskPer):'—';n('riskNote').textContent=action==='BUY'&&qty>0?`Risk-first sizing: ₹${Math.round(amt).toLocaleString('en-IN')} max planned risk; ${qty} share(s) at current scanner Entry/SL.`:'No actionable BUY sizing: wait for a confirmed BUY setup with valid Entry and SL.'}['riskCapital','riskPct'].forEach(id=>n(id)?.addEventListener('input',calc));window.calcRiskEngine=calc;setTimeout(calc,1500);setInterval(calc,5000)})();</script>'''
if 'id="risk-engine-js"' not in s:s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
