from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
style='''<style id="swingV2Style">.swing-v2{margin-top:8px;padding:10px;border:1px solid #dbe4ed;border-radius:12px;background:#fff}.swing-v2 h3{margin:0 0 7px;font-size:11px}.swing-card{margin-top:8px;padding:10px;border:1px solid #e1e9f1;border-radius:11px;background:#f9fbfd}.swing-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.swing-symbol{font-size:14px;font-weight:950}.swing-action{font-size:9px;font-weight:900;padding:4px 7px;border-radius:999px}.swing-action.buy{color:#07885f;background:#e9fbf4}.swing-action.wait{color:#9b7110;background:#fff8df}.swing-action.avoid{color:#c3314a;background:#fff0f2}.swing-meta{font-size:9px;color:#66778d;margin-top:5px;line-height:1.45}.swing-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px}.swing-k{background:#eef3f8;border-radius:7px;padding:5px}.swing-k small{display:block;font-size:7px;color:#718198}.swing-k b{font-size:9px}.swing-confirm{font-size:8px;color:#52647a;margin-top:7px;line-height:1.35}.swing-actions{display:flex;gap:6px;margin-top:7px}.swing-actions button,.swing-share{flex:1;display:inline-block;text-align:center;padding:7px;border-radius:8px;border:1px solid #d6e1eb;background:#fff;color:#0b2a52;text-decoration:none;font-size:8px;font-weight:850}.swing-actions .wa{background:#087dca;color:#fff;border-color:#087dca}.swing-v2 .buy{color:#079b6a}.swing-v2 .wait{color:#bd8610}.swing-v2 .avoid{color:#d94058}@media(max-width:380px){.swing-grid{grid-template-columns:repeat(2,1fr)}}</style>'''
if 'id="swingV2Style"' not in s:s=s.replace('</style>',style+'</style>',1)
panel='''<div class="swing-v2" id="swingV2"><h3>📈 SWING SCANNER • LIVE</h3><div id="swingV2List">Scanning confirmed setups…</div></div>'''
if 'id="swingV2"' not in s:
    marker='<button class="more-details" id="moreDetailsBtn" type="button">'
    if marker in s:s=s.replace(marker,panel+'\n'+marker,1)
script='''<script id="swingV2Script">\n(function(){\nfunction esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}\nfunction shareText(x){return `📈 NIFTY Sensex Sniper — Swing Setup\\n${x.symbol||'—'} | ${x.action||'WAIT'} | Score ${x.score||0}/10\\nSetup: ${x.setup||'—'}\\nHolding: ${x.holding_period||'—'}\\nEntry: ${x.entry??'—'} | SL: ${x.stoploss??'—'}\\nT1: ${x.target1??'—'} | T2: ${x.target2??'—'} | R:R: ${x.rr??'—'}\\nConfirmations: ${(x.confirmations||[]).join(', ')||'—'}\\nInvalidation: ${x.invalidation||'—'}\\nEducational/probabilistic only — not a guaranteed prediction.`}\nfunction addWatch(x){let a=JSON.parse(localStorage.getItem('sniperWatchlist')||'[]');const id=x.symbol||'';if(!a.includes(id))a.push(id);localStorage.setItem('sniperWatchlist',JSON.stringify(a));return a.length}\nasync function loadSwingV2(){const box=document.getElementById('swingV2List');if(!box)return;try{const r=await fetch('/api/swing?ts='+Date.now(),{cache:'no-store'}),d=await r.json();if(!d.ok){box.textContent='🛡️ Swing engine unavailable — NO SWING.';return}const rows=d.candidates||[];if(!rows.length){box.textContent='🛡️ No confirmed swing setup right now.';return}box.innerHTML=rows.slice(0,5).map((x,i)=>{const action=String(x.action||'WAIT').toUpperCase(),cls=action.toLowerCase(),watch=esc(x.symbol||'');const txt=encodeURIComponent(shareText(x));return `<div class="swing-card"><div class="swing-top"><span class="swing-symbol">${esc(x.symbol)}</span><span class="swing-action ${cls}">${esc(action)} • ${esc(x.score)}/10</span></div><div class="swing-meta">${esc(x.setup)} • ⏳ ${esc(x.holding_period)}</div><div class="swing-grid"><div class="swing-k"><small>ENTRY</small><b>${esc(x.entry)}</b></div><div class="swing-k"><small>SL</small><b>${esc(x.stoploss)}</b></div><div class="swing-k"><small>T1</small><b>${esc(x.target1)}</b></div><div class="swing-k"><small>R:R</small><b>${esc(x.rr)}</b></div></div><div class="swing-confirm">🧩 ${(x.confirmations||[]).map(esc).join(' • ')||'Confirmation pending'}<br>🏭 Sector: ${esc(x.sector_strength)} • 🧠 SMC: ${esc(x.smc?.status||x.smc)}</div><div class="swing-actions"><button type="button" data-watch="${watch}" data-index="${i}">👁️ Watchlist</button><a class="swing-share wa" target="_blank" rel="noopener" href="https://wa.me/?text=${txt}">📲 WhatsApp</a></div></div>`}).join('');box.querySelectorAll('[data-watch]').forEach(b=>b.addEventListener('click',()=>{const n=addWatch({symbol:b.dataset.watch});b.textContent=`✓ Saved (${n})`;b.disabled=true}))}catch(e){box.textContent='🛡️ Live swing confirmation unavailable.'}}\nwindow.loadSwingV2=loadSwingV2;loadSwingV2();setInterval(loadSwingV2,60000);\n})();\n</script>'''
if 'id="swingV2Script"' not in s:s=s.replace('</body>',script+'</body>',1)
p.write_text(s,encoding='utf-8')
