from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
style='''<style id="swingV2Style">.swing-v2{margin-top:6px;padding:8px;border:1px solid #dbe4ed;border-radius:9px;background:#fff}.swing-v2 h3{margin:0 0 5px;font-size:10px}.swing-card{padding:7px 0;border-bottom:1px solid #e7edf3}.swing-card:last-child{border:0}.swing-top{display:flex;justify-content:space-between;gap:8px;font-size:9px}.swing-meta{font-size:8px;color:#718198;margin-top:2px;line-height:1.3}.swing-share{display:inline-block;margin-top:4px;padding:4px 7px;border-radius:7px;background:#0b2a52;color:#fff;text-decoration:none;font-size:8px;font-weight:800}.swing-v2 .buy{color:#079b6a}.swing-v2 .wait{color:#bd8610}.swing-v2 .avoid{color:#d94058}</style>'''
if 'id="swingV2Style"' not in s:s=s.replace('</style>',style+'</style>',1)
# Put the live scanner inside the compact cockpit so it is reachable without disturbing the one-screen layout.
panel='''<div class="swing-v2" id="swingV2"><h3>📈 SWING SCANNER • LIVE</h3><div id="swingV2List">Scanning confirmed setups…</div></div>'''
if 'id="swingV2"' not in s:
    marker='<button class="more-details" id="moreDetailsBtn" type="button">'
    if marker in s:s=s.replace(marker,panel+'\n'+marker,1)
script='''<script id="swingV2Script">\n(function(){\nfunction esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}\nasync function loadSwingV2(){const box=document.getElementById('swingV2List');if(!box)return;try{const r=await fetch('/api/swing?ts='+Date.now(),{cache:'no-store'}),d=await r.json();if(!d.ok||!d.candidates?.length){box.textContent='🛡️ Live swing confirmation unavailable.';return}box.innerHTML=d.candidates.slice(0,5).map(x=>{const cls=String(x.action||'WAIT').toLowerCase();const share=encodeURIComponent(x.share_text||'');return `<div class="swing-card"><div class="swing-top"><b>${esc(x.symbol)}</b><b class="${cls}">${esc(x.action)} • ${esc(x.score)}/10</b></div><div class="swing-meta">${esc(x.setup)} • Holding: ${esc(x.holding_period)}<br>Entry ${esc(x.entry)} • SL ${esc(x.stoploss)} • T1 ${esc(x.target1)} • T2 ${esc(x.target2)} • R:R ${esc(x.rr)}</div>${share?`<a class="swing-share" target="_blank" rel="noopener" href="https://wa.me/?text=${share}">📲 WhatsApp</a>`:''}</div>`}).join('')}catch(e){box.textContent='🛡️ Live swing confirmation unavailable.'}}\nwindow.loadSwingV2=loadSwingV2;loadSwingV2();setInterval(loadSwingV2,60000);\n})();\n</script>'''
if 'id="swingV2Script"' not in s:s=s.replace('</body>',script+'</body>',1)
p.write_text(s,encoding='utf-8')
