const V2='https://api.upstox.com/v2',V3='https://api.upstox.com/v3';
const IDS={NIFTY:process.env.UPSTOX_NIFTY_KEY||'NSE_INDEX|Nifty 50',SENSEX:process.env.UPSTOX_SENSEX_KEY||'BSE_INDEX|SENSEX',VIX:process.env.UPSTOX_VIX_KEY||'NSE_INDEX|India VIX',GIFT:process.env.UPSTOX_GIFT_KEY||'GLOBAL_INDEX|SGX NIFTY',RELIANCE:process.env.UPSTOX_RELIANCE_KEY||'NSE_EQ|INE002A01018',HDFCBANK:process.env.UPSTOX_HDFCBANK_KEY||'NSE_EQ|INE040A01034',ICICIBANK:process.env.UPSTOX_ICICIBANK_KEY||'NSE_EQ|INE090A01021'};
const json=(r,s,b)=>{r.status(s).setHeader('Content-Type','application/json');r.setHeader('Cache-Control','no-store');return r.end(JSON.stringify(b))};
const headers=()=>{const t=process.env.UPSTOX_ACCESS_TOKEN;if(!t)throw Error('Upstox access token is not configured on Vercel.');return{Accept:'application/json',Authorization:`Bearer ${t}`}};
async function api(base,path,params={}){const u=new URL(base+path);Object.entries(params).forEach(([k,v])=>v!=null&&v!==''&&u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:headers(),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.status==='error')throw Error(d?.errors?.[0]?.message||d?.message||`Upstox HTTP ${r.status}`);return d}
function pick(d,key){const x=d?.data||{};return x[key]||x[key.replace('|',':')]||Object.entries(x).find(([k,v])=>k.replace(':','|')===key||v?.instrument_token===key)?.[1]||null}
function quote(q){if(!q)return null;const last=Number(q.last_price),ch=q.net_change==null?null:Number(q.net_change),prev=q.prev_close_price==null?Number(q.ohlc?.close):Number(q.prev_close_price);return{last_price:Number.isFinite(last)?last:null,change:Number.isFinite(ch)?ch:null,change_pct:Number.isFinite(prev)&&prev?ch/prev*100:null,timestamp:q.timestamp||null,last_trade_time:q.last_trade_time?new Date(Number(q.last_trade_time)).toISOString():null,volume:q.volume==null?null:Number(q.volume)}}
async function market(){const d=await api(V3,'/market-quote/quotes',{instrument_key:[IDS.NIFTY,IDS.SENSEX,IDS.VIX,IDS.GIFT].join(',')});const n=pick(d,IDS.NIFTY),s=pick(d,IDS.SENSEX),v=pick(d,IDS.VIX),g=pick(d,IDS.GIFT);const ts=[n?.timestamp,s?.timestamp,v?.timestamp,g?.timestamp].filter(Boolean).map(x=>new Date(x).getTime()).filter(Number.isFinite);return{nifty:quote(n),sensex:quote(s),vix:quote(v),gift_nifty:quote(g),provider:'Upstox',data_timestamp:ts.length?new Date(Math.max(...ts)).toISOString():null,fetched_at:new Date().toISOString()}}
async function leaders(){const d=await api(V3,'/market-quote/quotes',{instrument_key:[IDS.RELIANCE,IDS.HDFCBANK,IDS.ICICIBANK].join(',')});const one=(k,name)=>{const q=quote(pick(d,k));return q?{name,instrument_key:k,available:true,...q}:{name,instrument_key:k,available:false}};return{reliance:one(IDS.RELIANCE,'Reliance'),hdfcBank:one(IDS.HDFCBANK,'HDFC Bank'),iciciBank:one(IDS.ICICIBANK,'ICICI Bank'),fetched_at:new Date().toISOString()}}
function bars(raw){return(raw?.data?.candles||[]).map(x=>({ts:x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+(x[5]||0)})).sort((a,b)=>String(a.ts).localeCompare(String(b.ts)))}
async function candles(u){const raw=await api(V3,`/historical-candle/intraday/${encodeURIComponent(IDS[u])}/minutes/5`);const b=bars(raw).slice(-78);let pv=0,vol=0;b.forEach(x=>{pv+=(x.high+x.low+x.close)/3*(x.volume||0);vol+=x.volume||0});return{bars:b,vwap:vol?pv/vol:null}}
async function prevDay(u){const key=IDS[u],today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());const end=new Date(`${today}T00:00:00+05:30`);end.setUTCDate(end.getUTCDate()-1);const to=end.toISOString().slice(0,10),from=new Date(end);from.setUTCDate(from.getUTCDate()-7);const raw=await api(V3,`/historical-candle/${encodeURIComponent(key)}/days/1/${to}/${from.toISOString().slice(0,10)}`),r=bars(raw),x=r[r.length-1];if(!x)throw Error('Previous trading-day candle unavailable');return{date:String(x.ts).slice(0,10),high:x.high,low:x.low,close:x.close}}
async function contracts(u){const raw=await api(V2,'/option/contract',{instrument_key:IDS[u]}),a=Array.isArray(raw?.data)?raw.data:[],dates=[...new Set(a.map(x=>x.expiry).filter(Boolean))].sort(),today=new Date().toISOString().slice(0,10),future=dates.filter(x=>x>=today);return{expiry:future[0]||dates[0]||null,dates}}
function chainRows(raw,expiry){const rows=(raw?.data||[]).map(x=>({strike:+x.strike_price,call:x.call_options?{ltp:x.call_options.market_data?.ltp,oi:x.call_options.market_data?.oi,prevOi:x.call_options.market_data?.prev_oi,volume:x.call_options.market_data?.volume,iv:x.call_options.option_greeks?.iv}:null,put:x.put_options?{ltp:x.put_options.market_data?.ltp,oi:x.put_options.market_data?.oi,prevOi:x.put_options.market_data?.prev_oi,volume:x.put_options.market_data?.volume,iv:x.put_options.option_greeks?.iv}:null,spot:+(x.underlying_spot_price||0)})).sort((a,b)=>a.strike-b.strike);const spot=+rows.find(x=>x.spot>0)?.spot||0,atm=rows.reduce((b,x)=>!b||Math.abs(x.strike-spot)<Math.abs(b.strike-spot)?x:b,null),idx=atm?rows.findIndex(x=>x.strike===atm.strike):-1,co=rows.reduce((s,x)=>s+(+x.call?.oi||0),0),po=rows.reduce((s,x)=>s+(+x.put?.oi||0),0);return{expiry,spot,atm,pcr:co?po/co:null,rows:idx>=0?rows.slice(Math.max(0,idx-6),idx+7):rows.slice(0,13)}}
async function optionchain(u){const c=await contracts(u),raw=await api(V2,'/option/chain',{instrument_key:IDS[u],expiry_date:c.expiry});const s=chainRows(raw,c.expiry);if(!s.rows.length)throw Error(`Upstox returned no option-chain rows for ${u} ${c.expiry}.`);return{underlying:u,...s,expiryDates:c.dates}}
function avgVol(b){return b.slice(-11,-1).reduce((z,y)=>z+y.volume,0)/Math.max(1,Math.min(10,b.length-1))}
function smc(b){if(b.length<6)return{structure:'INSUFFICIENT',bos:'WAIT',choch:'WAIT',sweep:'NO SWEEP',fvg:'NONE',displacement:'NONE',order_block:'NONE'};const x=b[b.length-1],p=b[b.length-2],prior=b.slice(-6,-1),ph=Math.max(...prior.map(z=>z.high)),pl=Math.min(...prior.map(z=>z.low)),bullBos=x.close>ph,bearBos=x.close<pl,bullSweep=x.low<Math.min(...prior.slice(-3).map(z=>z.low))&&x.close>Math.min(...prior.slice(-3).map(z=>z.low)),bearSweep=x.high>Math.max(...prior.slice(-3).map(z=>z.high))&&x.close<Math.max(...prior.slice(-3).map(z=>z.high));const bullFvg=x.low>p.high,bearFvg=x.high<p.low,range=x.high-x.low,body=Math.abs(x.close-x.open),disp=range>0&&body/range>=.6&&x.volume>avgVol(b)*1.2;let ob='NONE';if(disp&&b.length>=3){const q=b[b.length-2];ob=q.close<q.open?'BULLISH OB':q.close>q.open?'BEARISH OB':'NONE'}return{structure:bullBos?'BULLISH BOS':bearBos?'BEARISH BOS':x.close>p.close?'BULLISH':'BEARISH',bos:bullBos?'BULLISH':bearBos?'BEARISH':'NONE',choch:bullSweep?'BULLISH CHoCH':bearSweep?'BEARISH CHoCH':'NONE',sweep:bullSweep?'BULLISH SWEEP':bearSweep?'BEARISH SWEEP':'NO SWEEP',fvg:bullFvg?'BULLISH FVG':bearFvg?'BEARISH FVG':'NONE',displacement:disp?(x.close>x.open?'BULLISH':'BEARISH'):'NONE',order_block:ob}}
function side(c){const b=c?.bars||[];if(b.length<2)return null;const x=b[b.length-1],p=b[b.length-2],above=c.vwap!=null&&x.close>c.vwap,below=c.vwap!=null&&x.close<c.vwap,dir=x.close>p.close?'BULLISH':x.close<p.close?'BEARISH':'MIXED',s=dir==='BULLISH'&&above?'BULLISH':dir==='BEARISH'&&below?'BEARISH':'MIXED';return{side:s,structure:dir,vwap:above?'Above VWAP':below?'Below VWAP':'At VWAP',volume_spike:x.volume>avgVol(b)*1.2,last:x.close,last_low:x.low,last_high:x.high,vwap_value:c.vwap,smc:smc(b)}}
function leaderSide(l){const a=[l.reliance,l.hdfcBank,l.iciciBank].filter(x=>x?.available),p=a.filter(x=>x.change>0).length,n=a.filter(x=>x.change<0).length;return p>=2?'BULLISH':n>=2?'BEARISH':'MIXED'}
function optSide(o){const c=o?.atm?.call,p=o?.atm?.put;if(!c||!p)return null;const dc=+c.oi-(+c.prevOi||0),dp=+p.oi-(+p.prevOi||0);return dc>0&&dp<0?'BEARISH':dc<0&&dp>0?'BULLISH':'MIXED'}
function volumeSide(n,s){const a=[n,s].filter(Boolean),bull=a.filter(x=>x.side==='BULLISH'&&x.volume_spike).length,bear=a.filter(x=>x.side==='BEARISH'&&x.volume_spike).length;return bull>=1&&bull>bear?'BULLISH':bear>=1&&bear>bull?'BEARISH':'MIXED'}
function smcSide(n,s){const a=[n?.smc,s?.smc].filter(Boolean),bull=a.filter(x=>x.bos==='BULLISH'||x.choch==='BULLISH'||x.sweep==='BULLISH SWEEP'||x.fvg==='BULLISH FVG').length,bear=a.filter(x=>x.bos==='BEARISH'||x.choch==='BEARISH'||x.sweep==='BEARISH SWEEP'||x.fvg==='BEARISH FVG').length;return bull>bear&&bull>=1?'BULLISH':bear>bull&&bear>=1?'BEARISH':'MIXED'}
function marketOpen(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),d=Object.fromEntries(p.map(x=>[x.type,x.value])),mins=+d.hour*60+(+d.minute);return !['Sat','Sun'].includes(d.weekday)&&mins>=555&&mins<=930}
function levels(verdict,spot,n,s){if(!spot||!['CALL','PUT'].includes(verdict))return null;const x=verdict==='CALL'?Math.min(n?.vwap_value||Infinity,n?.last_low||Infinity,s?.last_low||Infinity):Math.max(n?.vwap_value||-Infinity,n?.last_high||-Infinity,s?.last_high||-Infinity);const risk=Math.abs(spot-x);if(!Number.isFinite(x)||risk<=0||risk>spot*.01)return null;return{entry:spot,stop_loss:x,target1:verdict==='CALL'?spot+risk*1.5:spot-risk*1.5,target2:verdict==='CALL'?spot+risk*2.2:spot-risk*2.2,risk_reward_target1:'1:1.5'}}
async function engine(){const[m,n,s,l,o,nd,sd]=await Promise.all([market(),candles('NIFTY'),candles('SENSEX'),leaders(),optionchain('NIFTY'),prevDay('NIFTY'),prevDay('SENSEX')]);const ns=side(n),ss=side(s),ls=leaderSide(l),os=optSide(o),vs=volumeSide(ns,ss),smcs=smcSide(ns,ss),spot=+m.nifty?.last_price||0;const factors=[ns?.side,ss?.side,ls,os,vs,smcs].filter(Boolean);const bull=factors.filter(x=>x==='BULLISH').length,bear=factors.filter(x=>x==='BEARISH').length;const open=marketOpen(),fresh=m.data_timestamp?((Date.now()-new Date(m.data_timestamp).getTime())/1000):99999,freshOk=fresh<=300;const same=bull>=5&&bull>=bear+2?'CALL':bear>=5&&bear>=bull+2?'PUT':'NO TRADE',verdict=open&&freshOk?same:'NO TRADE';const liq=spot>nd.high?'PDH BREAK':spot<nd.low?'PDL BREAK':'NO SWEEP',conf=verdict==='NO TRADE'?Math.min(6.5,5+Math.abs(bull-bear)*.35):Math.min(9.5,7.5+Math.abs(bull-bear)*.4);return{verdict,confidence:+conf.toFixed(1),market_open:open,fresh_seconds:Math.max(0,Math.round(fresh)),fresh_ok:freshOk,spot,sensex_spot:m.sensex?.last_price||null,vix:m.vix?.last_price||null,gift_nifty:m.gift_nifty||null,nifty_bias:ns?.side||'MIXED',sensex_bias:ss?.side||'MIXED',factors:{nifty:ns,sensex:ss,leaders:ls,options:os,volume:vs,smc:smcs,liquidity:liq},pdh_pdl:{nifty:{pdh:nd.high,pdl:nd.low},sensex:{pdh:sd.high,pdl:sd.low}},expiry:o.expiry,pcr:o.pcr,atm:o.atm,levels:levels(verdict,spot,ns,ss),reason:!open?'Market closed — 5m confirmation waits for the next session.':!freshOk?'Exchange data is stale — wait for fresh data.':verdict==='NO TRADE'?`Confirmation ${Math.max(bull,bear)}/6 — need stronger alignment.`:`${verdict==='CALL'?'Bullish':'Bearish'} confirmation ${Math.max(bull,bear)}/6.`,fetched_at:new Date().toISOString()}}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'GET only'});try{if(!process.env.UPSTOX_ACCESS_TOKEN)return json(res,200,{live:false,provider:'Upstox',error:'Upstox access token is not configured yet.'});const a=req.query?.action||'status';if(a==='market')return json(res,200,{live:true,...await market()});if(a==='leaders')return json(res,200,{live:true,provider:'Upstox',...await leaders()});if(a==='expiry'){const[n,s]=await Promise.all([contracts('NIFTY'),contracts('SENSEX')]);return json(res,200,{live:true,nifty:n.dates,sensex:s.dates})}if(a==='chain'){const u=String(req.query?.underlying||'NIFTY').toUpperCase();return json(res,200,{live:true,provider:'Upstox',...await optionchain(u)})}if(a==='candles'){const u=String(req.query?.underlying||'NIFTY').toUpperCase();return json(res,200,{live:true,provider:'Upstox',underlying:u,...await candles(u)})}if(a==='engine')return json(res,200,{live:true,provider:'Upstox',...await engine()});return json(res,200,{live:true,provider:'Upstox',actions:['market','leaders','expiry','chain','candles','engine']})}catch(e){return json(res,502,{live:false,provider:'Upstox',error:e.message})}}
