const UPSTOX_V2='https://api.upstox.com/v2';
const UPSTOX_V3='https://api.upstox.com/v3';
const IDS={NIFTY:process.env.UPSTOX_NIFTY_KEY||'NSE_INDEX|Nifty 50',SENSEX:process.env.UPSTOX_SENSEX_KEY||'BSE_INDEX|SENSEX',VIX:process.env.UPSTOX_VIX_KEY||'NSE_INDEX|India VIX',RELIANCE:process.env.UPSTOX_RELIANCE_KEY||'NSE_EQ|INE002A01018',HDFCBANK:process.env.UPSTOX_HDFCBANK_KEY||'NSE_EQ|INE040A01034',ICICIBANK:process.env.UPSTOX_ICICIBANK_KEY||'NSE_EQ|INE090A01021'};
function json(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(body));}
function authHeaders(){const token=process.env.UPSTOX_ACCESS_TOKEN;if(!token)throw new Error('Upstox access token is not configured on Vercel.');return{Accept:'application/json',Authorization:`Bearer ${token}`};}
async function upstox(base,path,params={}){const url=new URL(`${base}${path}`);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,String(v));});const r=await fetch(url,{headers:authHeaders(),cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok||data.status==='error')throw new Error(data?.errors?.[0]?.message||data?.message||`Upstox HTTP ${r.status}`);return data;}
function pickQuote(data,key){const d=data?.data||{};return d[key]||d[key.replace('|',':')]||Object.entries(d).find(([k,v])=>k.replace(':','|')===key||v?.instrument_token===key)?.[1]||null;}
function quoteMeta(q){return{timestamp:q?.timestamp||null,last_trade_time:q?.last_trade_time?new Date(Number(q.last_trade_time)).toISOString():null};}
function marketSession(){const now=new Date();const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now);const get=t=>parts.find(x=>x.type===t)?.value;const weekday=get('weekday');const hour=Number(get('hour'));const minute=Number(get('minute'));const mins=hour*60+minute;const weekdayOk=!['Sat','Sun'].includes(weekday);const open=weekdayOk&&mins>=555&&mins<930;return{open,weekday,hour,minute};}
async function market(){const keys=[IDS.NIFTY,IDS.SENSEX,IDS.VIX].join(',');const data=await upstox(UPSTOX_V3,'/market-quote/quotes',{instrument_key:keys});const nifty=pickQuote(data,IDS.NIFTY),sensex=pickQuote(data,IDS.SENSEX),vix=pickQuote(data,IDS.VIX);const ts=[nifty?.last_trade_time,sensex?.last_trade_time,vix?.last_trade_time].filter(Boolean).map(x=>Number(x)).filter(Number.isFinite);const exchangeTs=ts.length?new Date(Math.max(...ts)).toISOString():null;return{nifty,sensex,vix,provider:'Upstox',data_timestamp:exchangeTs||nifty?.timestamp||null,fetched_at:new Date().toISOString(),session:marketSession(),meta:{nifty:quoteMeta(nifty),sensex:quoteMeta(sensex),vix:quoteMeta(vix)}};}
function normalizeStockQuote(q,key,name){if(!q)return{name,instrument_key:key,available:false};const last=Number(q.last_price),change=q.net_change==null?null:Number(q.net_change),prev=q.prev_close_price==null?(q.ohlc?.close==null?null:Number(q.ohlc.close)):Number(q.prev_close_price);const pct=prev&&change!=null?(change/prev)*100:null;return{name,instrument_key:key,last_price:Number.isFinite(last)?last:null,prev_close:prev!=null&&Number.isFinite(prev)?prev:null,change:change!=null&&Number.isFinite(change)?change:null,change_pct:pct!=null&&Number.isFinite(pct)?pct:null,volume:q.volume==null?null:Number(q.volume),data_timestamp:q.timestamp||null,last_trade_time:q.last_trade_time?new Date(Number(q.last_trade_time)).toISOString():null,available:true};}
async function leaders(){const keys=[IDS.RELIANCE,IDS.HDFCBANK,IDS.ICICIBANK].join(',');const raw=await upstox(UPSTOX_V3,'/market-quote/quotes',{instrument_key:keys});return{reliance:normalizeStockQuote(pickQuote(raw,IDS.RELIANCE),IDS.RELIANCE,'Reliance'),hdfcBank:normalizeStockQuote(pickQuote(raw,IDS.HDFCBANK),IDS.HDFCBANK,'HDFC Bank'),iciciBank:normalizeStockQuote(pickQuote(raw,IDS.ICICIBANK),IDS.ICICIBANK,'ICICI Bank'),fetched_at:new Date().toISOString()};}
function normalizeCandleRows(raw){return(raw?.data?.candles||[]).map(x=>({ts:x[0],open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]||0)})).sort((a,b)=>String(a.ts).localeCompare(String(b.ts)));}
async function candles(underlying){const key=IDS[underlying];if(!key)throw new Error('Unknown underlying');const raw=await upstox(UPSTOX_V3,`/historical-candle/intraday/${encodeURIComponent(key)}/minutes/5`);const bars=normalizeCandleRows(raw).slice(-78);let pv=0,vol=0;bars.forEach(b=>{const tp=(b.high+b.low+b.close)/3;pv+=tp*(b.volume||0);vol+=b.volume||0;});return{bars,vwap:vol?pv/vol:null,fetched_at:new Date().toISOString()};}
async function previousDay(underlying){const key=IDS[underlying];const now=new Date();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(now);const end=new Date(`${today}T00:00:00+05:30`);end.setUTCDate(end.getUTCDate()-1);const to=end.toISOString().slice(0,10);const from=new Date(end);from.setUTCDate(from.getUTCDate()-7);const fromDate=from.toISOString().slice(0,10);const raw=await upstox(UPSTOX_V3,`/historical-candle/${encodeURIComponent(key)}/days/1/${to}/${fromDate}`);const rows=normalizeCandleRows(raw);const last=rows[rows.length-1];if(!last)throw new Error('Previous trading-day candle unavailable');return{date:String(last.ts).slice(0,10),high:last.high,low:last.low,close:last.close};}
async function optionContracts(underlying){const key=IDS[underlying];if(!key)throw new Error('Unknown underlying');const raw=await upstox(UPSTOX_V2,'/option/contract',{instrument_key:key});const contracts=Array.isArray(raw?.data)?raw.data:[];const dates=[...new Set(contracts.map(x=>x.expiry).filter(Boolean))].sort();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());const future=dates.filter(d=>d>=today);return{contracts,expiry:future[0]||dates[0]||null,expiryDates:dates};}
function summarizeChain(raw,requestedExpiry){const rows=Array.isArray(raw?.data)?raw.data.map(x=>({strike:Number(x.strike_price),call:x.call_options?{ltp:x.call_options.market_data?.ltp,oi:x.call_options.market_data?.oi,prevOi:x.call_options.market_data?.prev_oi,volume:x.call_options.market_data?.volume,iv:x.call_options.option_greeks?.iv}:null,put:x.put_options?{ltp:x.put_options.market_data?.ltp,oi:x.put_options.market_data?.oi,prevOi:x.put_options.market_data?.prev_oi,volume:x.put_options.market_data?.volume,iv:x.put_options.option_greeks?.iv}:null,spot:Number(x.underlying_spot_price||0),pcrAtStrike:x.pcr})).sort((a,b)=>a.strike-b.strike):[];const spot=Number(rows.find(r=>r.spot>0)?.spot||0);const atm=rows.reduce((best,r)=>!best||Math.abs(r.strike-spot)<Math.abs(best.strike-spot)?r:best,null);const callOI=rows.reduce((s,r)=>s+Number(r.call?.oi||0),0),putOI=rows.reduce((s,r)=>s+Number(r.put?.oi||0),0);const idx=atm?rows.findIndex(r=>r.strike===atm.strike):-1;return{expiry:requestedExpiry,spot,atm,pcr:callOI?putOI/callOI:null,rows:idx>=0?rows.slice(Math.max(0,idx-6),idx+7):rows.slice(0,13)};}
async function optionchain(underlying,requested){const ci=await optionContracts(underlying);const expiry=ci.expiry||requested||'current_week';const raw=await upstox(UPSTOX_V2,'/option/chain',{instrument_key:IDS[underlying],expiry_date:expiry});const s=summarizeChain(raw,expiry);if(!s.rows.length)throw new Error(`Upstox returned no option-chain rows for ${underlying} ${expiry}.`);return{underlying,...s,expiryDates:ci.expiryDates,fetched_at:new Date().toISOString()};}
function sideFromCandle(c){if(!c?.bars?.length)return null;const b=c.bars,last=b[b.length-1],prev=b[b.length-2]||last;const bull=last.close>prev.close,above=c.vwap!=null&&last.close>c.vwap;return{side:bull&&above?'BULLISH':!bull&&!above?'BEARISH':'MIXED',structure:bull?'Bullish':'Bearish',vwap:above?'Above VWAP':'Below VWAP',volume:(last.volume||0)>=(prev.volume||1),last:last.close};}
function leaderSide(l){const a=[l.reliance,l.hdfcBank,l.iciciBank].filter(x=>x?.available);const p=a.filter(x=>Number(x.change)>0).length,n=a.filter(x=>Number(x.change)<0).length;return p>=2?'BULLISH':n>=2?'BEARISH':'MIXED';}
function optionSide(o){const ce=o?.atm?.call,pe=o?.atm?.put;if(!ce||!pe)return null;const dc=Number(ce.oi||0)-Number(ce.prevOi||0),dp=Number(pe.oi||0)-Number(pe.prevOi||0);if(dc>0&&dp<0)return'BEARISH';if(dc<0&&dp>0)return'BULLISH';return'MIXED';}
async function engine(){const [m,n,s,l,o,nd,sd]=await Promise.all([market(),candles('NIFTY'),candles('SENSEX'),leaders(),optionchain('NIFTY'),previousDay('NIFTY'),previousDay('SENSEX')]);const ns=sideFromCandle(n),ss=sideFromCandle(s),ls=leaderSide(l),os=optionSide(o);const factors=[ns?.side,ss?.side,ls,os].filter(Boolean);let bull=0,bear=0;factors.forEach(x=>{if(x==='BULLISH')bull++;if(x==='BEARISH')bear++;});const same=bull>=3?'CALL':bear>=3?'PUT':'NO TRADE';const sessionOpen=!!m.session?.open;const lastTrade=[m.nifty?.last_trade_time,m.sensex?.last_trade_time,m.vix?.last_trade_time].filter(Boolean).map(x=>Number(x)).filter(Number.isFinite);const fresh=lastTrade.length?Math.max(0,(Date.now()-Math.max(...lastTrade))/1000):99999;const freshOk=sessionOpen&&fresh<=300;const liquidity={nifty:{pdh:nd.high,pdl:nd.low},sensex:{pdh:sd.high,pdl:sd.low}};const spot=Number(m.nifty?.last_price||0);const sweep=spot>nd.high?'PDH BREAK':spot<nd.low?'PDL BREAK':'NO SWEEP';const verdict=freshOk?same:'NO TRADE';const confidence=verdict==='NO TRADE'?Math.min(6.5,5+Math.abs(bull-bear)*0.5):Math.min(9.5,6.5+Math.abs(bull-bear)*0.75);return{verdict,confidence:Number(confidence.toFixed(1)),fresh_seconds:Math.max(0,Math.round(fresh)),fresh_ok:freshOk,market_open:sessionOpen,session:m.session,factors:{nifty:ns,sensex:ss,leaders:ls,options:os,liquidity:sweep},pdh_pdl:liquidity,spot,market:{nifty:m.nifty,sensex:m.sensex,vix:m.vix},leaders:l,expiry:o.expiry,pcr:o.pcr,atm:o.atm,reason:!sessionOpen?'Market closed — 5m confirmation waits for the next session.':verdict==='NO TRADE'?'Conflicting or insufficient confirmation — wait.':`${bull>bear?'Bullish':'Bearish'} factors aligned ${Math.max(bull,bear)}/4.`,fetched_at:new Date().toISOString()};}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'GET only'});const action=req.query?.action||'status';try{if(!process.env.UPSTOX_ACCESS_TOKEN)return json(res,200,{live:false,provider:'Upstox',error:'Upstox access token is not configured yet.'});if(action==='market')return json(res,200,{live:true,...(await market())});if(action==='leaders')return json(res,200,{live:true,provider:'Upstox',...(await leaders())});if(action==='expiry'){const[n,s]=await Promise.all([optionContracts('NIFTY'),optionContracts('SENSEX')]);return json(res,200,{live:true,provider:'Upstox',nifty:n.expiryDates,sensex:s.expiryDates});}if(action==='chain'){const u=String(req.query?.underlying||'NIFTY').toUpperCase();return json(res,200,{live:true,provider:'Upstox',...(await optionchain(u,req.query?.expiry))});}if(action==='candles'){const u=String(req.query?.underlying||'NIFTY').toUpperCase();return json(res,200,{live:true,provider:'Upstox',underlying:u,...(await candles(u))});}if(action==='engine')return json(res,200,{live:true,provider:'Upstox',...(await engine())});return json(res,200,{live:true,provider:'Upstox',actions:['market','leaders','expiry','chain','candles','engine']});}catch(e){return json(res,502,{live:false,provider:'Upstox',error:e.message});}}
