const FEEDS=[
  ['NIFTY / SENSEX','https://news.google.com/rss/search?q=NIFTY+SENSEX+India+stock+market&hl=en-IN&gl=IN&ceid=IN:en'],
  ['RBI / Economy','https://news.google.com/rss/search?q=RBI+India+inflation+economy&hl=en-IN&gl=IN&ceid=IN:en'],
  ['Global / Fed','https://news.google.com/rss/search?q=Federal+Reserve+oil+markets+India&hl=en-IN&gl=IN&ceid=IN:en']
];
const BULL=['rally','surge','gains','gain','rebound','recovery','strong growth','inflow','inflows','rate cut','cuts rates','dovish','beats','upgrade','bullish','record high','stimulus','eases'];
const BEAR=['crash','plunge','fall','falls','fell','selloff','sell-off','slump','weak','outflow','outflows','rate hike','hike rates','hawkish','inflation','war','attack','iran','israel','tariff','recession','default','crude oil surge','oil surge','yields rise','rupee weak','geopolitical'];
const RISK=['war','attack','iran','israel','crude','oil','inflation','tariff','fed','federal reserve','rbi','yield','geopolitical','recession','default'];
function clean(s=''){return s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/\s+/g,' ').trim()}
function parse(xml,category){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,8).map(m=>{const x=m[1],pick=t=>{const z=x.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`));return z?clean(z[1]):''};return{category,title:pick('title'),published:pick('pubDate')}}).filter(x=>x.title&&x.published)}
function norm(s){return s.toLowerCase().replace(/&[^;]+;/g,' ').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function words(s){return new Set(norm(s).split(' ').filter(w=>w.length>3))}
function similar(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return false;let hit=0;for(const w of A)if(B.has(w))hit++;return hit/Math.min(A.size,B.size)>=0.72}
function ageWeight(date,now){const ms=now-new Date(date).getTime(),h=ms/36e5;if(!Number.isFinite(h)||h<0)return 0;return h<=3?1:h<=12?.75:h<=24?.5:h<=48?.25:0}
function rawScore(title){const s=title.toLowerCase();let n=0;for(const k of BULL)if(s.includes(k))n++;for(const k of BEAR)if(s.includes(k))n--;return Math.max(-3,Math.min(3,n))}
function classify(tagged){const active=tagged.filter(x=>x.weight>0);const score=active.reduce((z,x)=>z+x.score*x.weight,0);const rounded=Math.round(score);const side=rounded>=2?'BULLISH':rounded<=-2?'BEARISH':'MIXED';const riskHits=active.filter(x=>x.risk).reduce((z,x)=>z+x.weight,0);const risk= riskHits>=2.5||Math.abs(score)>=5?'HIGH':riskHits>=1||Math.abs(score)>=2.5?'MEDIUM':'LOW';return{side,risk,score:rounded,raw_score:+score.toFixed(2),headline_count:active.length,unique_count:tagged.length,fresh_count:tagged.filter(x=>x.weight>=.75).length,ignored_count:tagged.filter(x=>x.weight===0).length,risk_headlines:+riskHits.toFixed(2),weights:'<=3h 1.00 • <=12h 0.75 • <=24h 0.50 • <=48h 0.25 • older ignored'}}
module.exports=async(req,res)=>{res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');try{const now=Date.now(),all=[];for(const [category,url] of FEEDS){const r=await fetch(url,{cache:'no-store',headers:{'User-Agent':'NIFTY-Sensex-Sniper/1.1'}});if(r.ok)all.push(...parse(await r.text(),category))}all.sort((a,b)=>new Date(b.published)-new Date(a.published));const seen=[],tagged=[];for(const item of all){if(seen.some(x=>similar(x.title,item.title)))continue;seen.push(item);const weight=ageWeight(item.published,now);const score=rawScore(item.title);const risk=RISK.some(k=>item.title.toLowerCase().includes(k));tagged.push({...item,weight,score,risk,age_hours:Number(((now-new Date(item.published).getTime())/36e5).toFixed(1))})}const summary=classify(tagged);res.status(200).end(JSON.stringify({ok:true,generated_at:new Date().toISOString(),engine_version:'News Intelligence V2',...summary,items:tagged.slice(0,12),disclaimer:'News is contextual information. Recency and duplicate weighting reduce stale or repeated headlines. News is not a standalone CALL/PUT trigger or financial advice.'}))}catch(e){res.status(500).end(JSON.stringify({ok:false,error:e.message,engine_version:'News Intelligence V2'}))}};
