// Swing Engine V3 — live conservative educational scanner with sector + structure gates.
const TOKEN=process.env.UPSTOX_ACCESS_TOKEN||'';
const H={Accept:'application/json',...(TOKEN?{Authorization:`Bearer ${TOKEN}`}:{})};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null},round=(v,d=2)=>v==null?null:Number(Number(v).toFixed(d));
const STOCKS=[['RELIANCE','NSE_EQ|INE002A01018','ENERGY'],['HDFCBANK','NSE_EQ|INE040A01034','BANKING'],['ICICIBANK','NSE_EQ|INE090A01021','BANKING'],['INFY','NSE_EQ|INE009A01021','IT'],['TCS','NSE_EQ|INE467B01029','IT'],['SBIN','NSE_EQ|INE062A01020','BANKING'],['LT','NSE_EQ|INE018A01030','CAPITAL_GOODS'],['AXISBANK','NSE_EQ|INE238A01034','BANKING'],['BHARTIARTL','NSE_EQ|INE397D01024','TELECOM'],['ITC','NSE_EQ|INE154A01025','FMCG'],['MARUTI','NSE_EQ|INE585B01010','AUTO'],['SUNPHARMA','NSE_EQ|INE044A01036','PHARMA']];
const NIFTY='NSE_INDEX|Nifty 50';
async function api(path){if(!TOKEN)throw Error('Upstox token missing');const u=new URL('https://api.upstox.com/v3'+path);const r=await fetch(u,{headers:H,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.status==='error')throw Error(d?.errors?.[0]?.message||d?.message||`Upstox HTTP ${r.status}`);return d}
function dates(){const now=new Date(),to=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(now),fromDate=new Date(now);fromDate.setUTCDate(fromDate.getUTCDate()-210);return{to,from:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(fromDate)}}
function candles(d){return(d?.data?.candles||[]).map(x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+(x[5]||0)})).sort((a,b)=>String(a.ts).localeCompare(String(b.ts)))}
const avg=(a,n)=>a.slice(-n).reduce((s,x)=>s+x,0)/Math.max(1,Math.min(n,a.length));
const ema=(a,n)=>{if(a.length<n)return null;let e=avg(a.slice(0,n),n),k=2/(n+1);for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function swingStructure(c){const last=c.at(-1),prev=c.at(-2),p=c.slice(-15,-1);const sh=Math.max(...p.map(x=>x.h)),sl=Math.min(...p.map(x=>x.l));const bos=last.c>sh||last.c<sl;const direction=last.c>sh?'BULLISH':last.c<sl?'BEARISH':'NEUTRAL';const range=Math.max(0,last.h-last.l),body=Math.abs(last.c-last.o);const displacement=range>0&&body/range>=0.65&&last.v>avg(c.slice(-21,-1).map(x=>x.v),20)*1.15;const demand=last.c>prev.c&&last.l<=ema(c.map(x=>x.c),20)*1.015;const supply=last.c<prev.c&&last.h>=ema(c.map(x=>x.c),20)*0.985;return{bos:bos?direction:'NONE',displacement:displacement?'YES':'NO',zone:demand?'DEMAND':supply?'SUPPLY':'NEUTRAL'}}
function analyse(symbol,b,nifty,sectorRet){const c=b.slice(-90);if(c.length<55)return null;const closes=c.map(x=>x.c),vols=c.map(x=>x.v),e20=ema(closes,20),e50=ema(closes,50),last=c.at(-1),prev=c.at(-2),prior20=c.slice(-21,-1),high20=Math.max(...prior20.map(x=>x.h)),av=avg(vols.slice(-21,-1),20),ret20=closes.at(-1)/closes.at(-21)-1,nret=nret20(nifty),rs=ret20-nret,trend=e20>e50,weekly=c.slice(-25).at(-1).c>c.slice(-25).at(0).c,breakout=last.c>high20,pullback=last.c>e20&&last.l<=e20*1.015&&last.c>prev.c,vol=last.v>av*1.25,nearBreak=last.c>=high20*0.985&&last.c<=high20*1.03,smc=swingStructure(c),sectorStrength=sectorRet!=null&&ret20-sectorRet>0.01,setup=breakout&&vol?'BREAKOUT':breakout&&nearBreak?'BREAKOUT_RETEST':pullback?'PULLBACK_DEMAND':'WATCH';let score=0,why=[];if(trend){score+=1.5;why.push('Daily trend')}if(weekly){score+=1;why.push('Weekly momentum')}if(vol){score+=1.5;why.push('Volume expansion')}if(rs>0.03){score+=1.5;why.push('Relative strength')}else if(rs>0){score+=.5;why.push('Relative strength')}if(breakout){score+=2;why.push('20D breakout')}else if(nearBreak){score+=1;why.push('Near breakout')}if(pullback){score+=1;why.push('EMA20 pullback')}if(sectorStrength){score+=1;why.push('Sector strength')}if(smc.bos==='BULLISH'&&smc.displacement==='YES'){score+=1;why.push('SMC BOS + displacement')}else if(smc.zone==='DEMAND'){score+=.5;why.push('Demand zone')}if(last.c>prev.c){score+=.5;why.push('Price confirmation')}score=Math.min(10,round(score,1));const structureBull=smc.bos==='BULLISH'||smc.zone==='DEMAND';let action=score>=8&&trend&&vol&&structureBull?'BUY':score>=6.5?'WAIT':'AVOID';if(!trend||!vol||!structureBull)action=action==='BUY'?'WAIT':action;const entry=action==='BUY'?last.c:null,sl=action==='BUY'?Math.min(last.l,e20*0.985):null,risk=entry&&sl&&entry>sl?entry-sl:null,target1=risk?entry+risk*1.5:null,target2=risk?entry+risk*2.5:null,holding=score>=8?'3–7 trading sessions':score>=7?'1–3 weeks':'WATCH',invalidation=sl?`Daily close below ${round(sl)}`:'Wait for confirmation';return{symbol,score,action,setup,holding_period:holding,entry:entry?round(entry):null,stoploss:sl?round(sl):null,target1:target1?round(target1):null,target2:target2?round(target2):null,rr:risk?'1:1.5 / 1:2.5':null,invalidation,confirmations:why,relative_strength_pct:round(rs*100,2),sector_strength:sectorStrength?'STRONG':'NORMAL',smc,trend:trend?'BULLISH':'BEARISH',volume:vol?'STRONG':'NORMAL',reason:action==='BUY'?'Confirmed swing setup: trend + volume + structure aligned.':action==='WAIT'?'Setup forming; wait for confirmation.':'Insufficient swing confirmation.'}}
function nret20(n){if(!n||n.length<21)return 0;return n.at(-1).c/n.at(-21).c-1}
export default async function handler(req,res){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');try{const d=dates(),path=k=>`/historical-candle/${encodeURIComponent(k)}/days/1/${d.to}/${d.from}`,nd=candles(await api(path(NIFTY)));const sectorBase={};for(const s of ['BANKING','IT','ENERGY','CAPITAL_GOODS','TELECOM','FMCG','AUTO','PHARMA'])sectorBase[s]=null;const raw=await Promise.all(STOCKS.map(async([symbol,key,sector])=>{try{return{symbol,key,sector,c:candles(await api(path(key)))}}catch(e){return null}}));const valid=raw.filter(Boolean);for(const [symbol,key,sector] of STOCKS){const r=valid.find(x=>x.symbol===symbol);if(r?.c?.length>=21){const rr=r.c.at(-1).c/r.c.at(-21).c-1;sectorBase[sector]=sectorBase[sector]==null?rr:Math.max(sectorBase[sector],rr)}}const candidates=valid.map(x=>analyse(x.symbol,x.c,nd,sectorBase[x.sector])).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,8);res.status(200).end(JSON.stringify({ok:true,engine_version:'Swing Engine V3',universe:'Liquid NIFTY basket — live scan',generated_at:new Date().toISOString(),candidates,actionable_count:candidates.filter(x=>x.action==='BUY').length,filters:['Weekly/Daily trend','20D breakout/retest','EMA20 pullback','Volume expansion','Relative strength vs NIFTY','Sector strength','SMC BOS/displacement/demand','Risk/Reward','Invalidation','Holding period'],disclaimer:'Educational/probabilistic only. Entry, stop and targets are heuristic levels, not guaranteed outcomes or financial advice.'}))}catch(e){res.status(200).end(JSON.stringify({ok:false,engine_version:'Swing Engine V3',universe:'Liquid NIFTY basket',candidates:[],error:String(e.message||e),disclaimer:'Educational/probabilistic only.'}))}}
