// Swing Engine V2 — live, conservative, educational scanner.
const TOKEN=process.env.UPSTOX_ACCESS_TOKEN||'';
const H={Accept:'application/json',...(TOKEN?{Authorization:`Bearer ${TOKEN}`}:{})};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null},round=(v,d=2)=>v==null?null:Number(Number(v).toFixed(d));
const STOCKS=[['RELIANCE','NSE_EQ|INE002A01018'],['HDFCBANK','NSE_EQ|INE040A01034'],['ICICIBANK','NSE_EQ|INE090A01021'],['INFY','NSE_EQ|INE009A01021'],['TCS','NSE_EQ|INE467B01029'],['SBIN','NSE_EQ|INE062A01020'],['LT','NSE_EQ|INE018A01030'],['AXISBANK','NSE_EQ|INE238A01034'],['BHARTIARTL','NSE_EQ|INE397D01024'],['ITC','NSE_EQ|INE154A01025'],['MARUTI','NSE_EQ|INE585B01010'],['SUNPHARMA','NSE_EQ|INE044A01036']];
const NIFTY='NSE_INDEX|Nifty 50';
async function api(path,params={}){if(!TOKEN)throw Error('Upstox token missing');const u=new URL('https://api.upstox.com/v3'+path);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:H,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.status==='error')throw Error(d?.errors?.[0]?.message||d?.message||`Upstox HTTP ${r.status}`);return d}
function candles(d){return(d?.data?.candles||[]).map(x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+(x[5]||0)})).sort((a,b)=>String(a.ts).localeCompare(String(b.ts)))}
const avg=(a,n)=>a.slice(-n).reduce((s,x)=>s+x,0)/Math.max(1,Math.min(n,a.length));
const ema=(a,n)=>{if(a.length<n)return null;let e=avg(a.slice(0,n),n),k=2/(n+1);for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function analyse(symbol,b,nifty){const c=b.slice(-90);if(c.length<55)return null;const closes=c.map(x=>x.c),vols=c.map(x=>x.v),e20=ema(closes,20),e50=ema(closes,50),last=c.at(-1),prev=c.at(-2),prior20=c.slice(-21,-1),high20=Math.max(...prior20.map(x=>x.h)),low20=Math.min(...prior20.map(x=>x.l)),av=avg(vols.slice(-21,-1),20),ret20=closes.at(-1)/closes.at(-21)-1,nret=nifty? nret20(nifty):0,rs=ret20-nret,breakout=last.c>high20,pullback=last.c>e20&&last.l<=e20*1.015&&last.c>prev.c,vol=last.v>av*1.25,trend=e20>e50,weekly=c.slice(-25).at(-1).c>c.slice(-25).at(0).c,nearBreak=last.c>=high20*0.985&&last.c<=high20*1.03,setup=breakout&&vol?'BREAKOUT':breakout&&nearBreak?'BREAKOUT_RETEST':pullback?'PULLBACK_EMA20':'WATCH';
let score=0,why=[];if(trend){score+=1.5;why.push('Daily trend')}if(weekly){score+=1;why.push('Weekly momentum')}if(vol){score+=1.5;why.push('Volume expansion')}if(rs>0.03){score+=1.5;why.push('Relative strength')}else if(rs>0){score+=.5}if(breakout){score+=2;why.push('20D breakout')}else if(nearBreak){score+=1;why.push('Near breakout')}if(pullback){score+=1;why.push('EMA20 pullback')}if(last.c>prev.c){score+=.5;why.push('Price confirmation')}score=Math.min(10,round(score,1));let action=score>=8&&trend&&vol?'BUY':score>=6.5?'WAIT':'AVOID';if(!trend&&score>=8)action='WAIT';const entry=action==='BUY'?last.c:null,sl=action==='BUY'?Math.min(last.l,e20*0.985):null,risk=entry&&sl&&entry>sl?entry-sl:null;const target1=risk?entry+risk*1.5:null,target2=risk?entry+risk*2.5:null;const holding=score>=8?'3–7 trading sessions':score>=7?'1–3 weeks':'WATCH';const invalidation=sl?`Daily close below ${round(sl)}`:'Wait for confirmation';const share=`🎯 NIFTY SENSEX SNIPER\n\n📈 SWING SETUP\nStock: ${symbol}\nBias: ${action==='BUY'?'🟢 BULLISH':'🟡 WAIT'}\nSetup: ${setup}\nScore: ${score}/10\nEntry: ${entry?round(entry):'Wait'}\nStop Loss: ${sl?round(sl):'Wait'}\nTarget 1: ${target1?round(target1):'—'}\nTarget 2: ${target2?round(target2):'—'}\nR:R: ${risk?'1:1.5 / 1:2.5':'—'}\nHolding: ${holding}\nInvalidation: ${invalidation}\n\nConfirmations: ${why.join(', ')||'Insufficient'}\n\nEducational/probabilistic only. Not financial advice.`;return{symbol,score,action,setup,holding_period:holding,entry:entry?round(entry):null,stoploss:sl?round(sl):null,target1:target1?round(target1):null,target2:target2?round(target2):null,rr:risk?'1:1.5 / 1:2.5':null,invalidation,confirmations:why,relative_strength_pct:round(rs*100,2),trend:trend?'BULLISH':'BEARISH',volume:vol?'STRONG':'NORMAL',share_text:share}}
function nret20(n){if(!n||n.length<21)return 0;return n.at(-1).c/n.at(-21).c-1}
export default async function handler(req,res){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');try{const nd=candles(await api(`/historical-candle/${encodeURIComponent(NIFTY)}/days/1/2026-09-12/2026-03-01`));const tasks=STOCKS.map(async([symbol,key])=>{try{return analyse(symbol,candles(await api(`/historical-candle/${encodeURIComponent(key)}/days/1/2026-09-12/2026-03-01`)),nd)}catch(e){return null}});const candidates=(await Promise.all(tasks)).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,8);const actionable=candidates.filter(x=>x.action==='BUY');res.status(200).end(JSON.stringify({ok:true,engine_version:'Swing Engine V2',universe:'Liquid NIFTY basket — V2 live scan',generated_at:new Date().toISOString(),candidates,actionable_count:actionable.length,filters:['Weekly/Daily trend','20D breakout/retest','EMA20 pullback','Volume expansion','Relative strength vs NIFTY','Risk/Reward','Invalidation','Holding period'],disclaimer:'Educational/probabilistic only. Entry, stop and targets are heuristic levels, not guaranteed outcomes or financial advice.'}))}catch(e){res.status(200).end(JSON.stringify({ok:false,engine_version:'Swing Engine V2',universe:'Liquid NIFTY basket',candidates:[],error:String(e.message||e),disclaimer:'Educational/probabilistic only.'}))}}
